### ISSUE TITLE
Let's cooperate!

### ISSUE THREAD

**Issue by vlad20012** [kryptan/webinden#2]
Hi, @kryptan!
I'm currently working on rust-webplatform fork, and thinking about how it should be arranged brought me to your repo :)

I've already set up automated tests (via Selenium), travis and bors ([PR](https://github.com/irbis-labs/rust-webplatform/pull/3)) ([test example](https://github.com/irbis-labs/rust-webplatform/commit/ce2509605719a4c40f1c36f8d83b5ae75d4a71ef#diff-97e5be657bf7f299a182f664a56168e2R287)) and now I'm working on JS type system, inheritance and memory management ([WIP PR](https://github.com/vlad20012/rust-webplatform/pull/2)). And I tend to use bindgen similar to yours in the future.

Maybe this stuff will be interesting to you :)

**Comment by kryptan** [comment]
Hello.

This repo is just a very beginning, not much is done yet, it is an experimentation stage. Also I don't yet pushed my latest changes so what you see here is not the latest version. My plan is to make complete bindings to web APIs so that you never have to use inline JS or anything similar with as much rusty API as possible.

P.S. Besides rust-webplatform there is also [stdweb](https://github.com/koute/stdweb) crate which seems to be actively developed.

**Comment by vlad20012** [comment]
Hmm, I did not mentioned stdweb. Thanks!

**Comment by vlad20012** [comment]
* noticed, I mean =D

"stdweb" is a really cool project. I think I should contribute there instead. The problem is that it is totally ungooglable, so I managed to find only webplatform...
